// Bundles the Lucide icons we use (https://lucide.dev, ISC licence) into public/js/icons.js so the app stays offline-friendly.
// To use another icon: add its name below, run `npm run icons`, then icon('name') in the views.
const fs = require('fs');
const path = require('path');

const NAMES = `house calendar-days tree-palm user-round settings qr-code scan-line camera check circle-check x clock timer download users
bell lock palette image log-out log-in plus search printer refresh-cw monitor pencil chevron-left chevron-right file-spreadsheet heart sun moon
thermometer briefcase sparkles hourglass shield-check triangle-alert layout-dashboard calendar-check calendar-x message-circle send trash-2
flashlight flashlight-off smartphone building-2 map-pin party-popper leaf flame circle-x circle-alert info key-round upload star umbrella
coffee user-cog sliders-horizontal list-checks wallet languages`.split(/\s+/).filter(Boolean);

const dir = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const entries = NAMES.map((n) => {
  const svg = fs.readFileSync(path.join(dir, `${n}.svg`), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s+/g, ' ').trim();
  return `  '${n}': '${inner.replace(/'/g, "\\'")}',`;
});

fs.writeFileSync(path.join(__dirname, '..', 'public', 'js', 'icons.js'), `// generated by scripts/build-icons.js — Lucide icons (ISC licence)
const PATHS = {
${entries.join('\n')}
};

export function icon(name, size = 20, cls = '') {
  const body = PATHS[name];
  if (!body) return '';
  return \`<svg class="ic \${cls}" viewBox="0 0 24 24" width="\${size}" height="\${size}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${body}</svg>\`;
}
`);
console.log(`wrote ${NAMES.length} icons`);
