// Copies third-party browser assets (jsQR + Mali font) into public/ so the app is self-contained
// (works offline as a PWA and can be wrapped by Capacitor later without a CDN).
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const out = (p) => path.join(root, 'public', p);
fs.mkdirSync(out('vendor'), { recursive: true });
fs.mkdirSync(out('fonts'), { recursive: true });

fs.copyFileSync(path.join(root, 'node_modules/jsqr/dist/jsQR.js'), out('vendor/jsQR.js'));

const fontDir = path.join(root, 'node_modules/@fontsource/mali/files');
const ranges = {
  thai: 'U+02D7,U+0303,U+0331,U+0E01-0E5B,U+200C-200D,U+25CC',
  latin: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
};
let css = '/* generated by scripts/copy-vendor.js */\n';
for (const weight of [400, 600, 700]) {
  for (const [subset, range] of Object.entries(ranges)) {
    const file = `mali-${subset}-${weight}-normal.woff2`;
    fs.copyFileSync(path.join(fontDir, file), out(`fonts/${file}`));
    css += `@font-face{font-family:'Mali';font-style:normal;font-display:swap;font-weight:${weight};` +
      `src:url(../fonts/${file}) format('woff2');unicode-range:${range}}\n`;
  }
}
fs.mkdirSync(out('css'), { recursive: true });
fs.writeFileSync(out('css/fonts.css'), css);
console.log('vendor assets copied');
